<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BnlCommunityFixes.Core\BnlCommunityFixes.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BnlCommunityFixes</AssemblyName>
    <RootNamespace>BnlCommunityFixes.Launcher</RootNamespace>
  </PropertyGroup>

</Project>
