<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BnlCommunityFixes.Core\BnlCommunityFixes.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>2.1.14</Version>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BnlCommunityFixes</AssemblyName>
    <RootNamespace>BnlCommunityFixes.Launcher</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>launcher-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="launcher-icon.ico" />
    <EmbeddedResource Include="game-icon.ico" />
    <EmbeddedResource Include="..\..\assets\patching\Build-ExperimentalCrosshairAssembly.ps1" LogicalName="Patching.Build-ExperimentalCrosshairAssembly.ps1" />
    <EmbeddedResource Include="..\..\assets\patching\CrosshairBundleRuntime.cs" LogicalName="Patching.CrosshairBundleRuntime.cs" />
    <EmbeddedResource Include="..\..\assets\patching\Mono.Cecil.dll" LogicalName="Patching.Mono.Cecil.dll" />
  </ItemGroup>

</Project>
